### PR TITLE
Waiting of the code review from TSE

### PR DESCRIPTION
**Pull request by ViriCruz**

### CODE REVIEW

**Comment by bellom** [comment]
## Currently reviewing this PR

**Review by bellom — APPROVED** [review]
Hi @ViriCruz,
## Congratulation :+1: 
Great job working alone, your methods works fine.
Goodluck in the next project.
Hint: Always add lint before you start to work on a project.

**Comment by ViriCruz** [comment]
The main curriculum said this is a solo project. Thanks for the hint.

**Comment by bellom** [comment]
Opps !! 
I checked it now
Made a mistake, thought - testing project.

**Pull request merged**
